numbers = (10, 20, 30, 40, 50)
print("Tuple:", numbers)
print("First element:", numbers[0])
print("Second element:", numbers[1])
print("Last element:", numbers[-1])
print("Second last element:", numbers[-2])
